import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import yaml from 'js-yaml';
import { Soul } from '../core/models/soul.js';
import { Persona } from '../core/models/persona.js';

/**
 * OpenClaw Exporter — generates an Agent Markdown file bundle:
 *   - SOUL.md       — soul dimensions as structured prose
 *   - IDENTITY.md   — persona metadata
 *   - MEMORY.md     — placeholder for memory nodes (full export for LobeChat/Clewbot)
 *
 * Load with: `openclaw agents import ./export/`
 */
export class OpenClawExporter {
  export(soul: Soul, persona: Persona, outputDir: string): void {
    mkdirSync(outputDir, { recursive: true });

    writeFileSync(join(outputDir, 'SOUL.md'), this.generateSoulMd(soul), 'utf-8');
    writeFileSync(join(outputDir, 'IDENTITY.md'), this.generateIdentityMd(persona, soul), 'utf-8');
    writeFileSync(join(outputDir, 'MEMORY.md'), this.generateMemoryMd(persona), 'utf-8');
    writeFileSync(join(outputDir, 'soul.yaml'), yaml.dump(soul), 'utf-8');
    writeFileSync(join(outputDir, 'agent.json'), this.generateAgentJson(soul, persona), 'utf-8');
  }

  private generateSoulMd(soul: Soul): string {
    const lines: string[] = [
      `# Soul Profile: ${soul.target_name}`,
      '',
      `> Generated by Nico v${soul.version} | Confidence: ${(soul.overall_confidence * 100).toFixed(0)}% | ${soul.total_chunks_processed} content pieces analyzed`,
      '',
      '## Language Style',
      '',
      `- **Formality**: ${this.formalityLabel(soul.language_style.formality_level)}`,
      `- **Sentence Length**: ${soul.language_style.avg_sentence_length}`,
      `- **Humor**: ${soul.behavioral_traits.humor_style}`,
      `- **Languages**: ${soul.language_style.languages_used.join(', ') || 'English'}`,
      '',
    ];

    if (soul.language_style.frequent_phrases.length > 0) {
      lines.push('**Characteristic Phrases:**');
      for (const p of soul.language_style.frequent_phrases.slice(0, 10)) {
        lines.push(`- "${p}"`);
      }
      lines.push('');
    }

    lines.push('## Core Values & Beliefs', '');
    for (const b of soul.values.core_beliefs.slice(0, 10)) {
      lines.push(
        `- **${b.belief}** _(${b.stance}, ${(b.confidence * 100).toFixed(0)}% confidence)_`
      );
    }
    lines.push('');

    lines.push('## Thinking Patterns', '');
    if (soul.thinking_patterns.problem_solving_approach) {
      lines.push(`**Problem-solving**: ${soul.thinking_patterns.problem_solving_approach}`, '');
    }
    if (soul.thinking_patterns.reasoning_style.length > 0) {
      lines.push('**Reasoning style:**');
      for (const r of soul.thinking_patterns.reasoning_style.slice(0, 6)) {
        lines.push(`- ${r.value}`);
      }
      lines.push('');
    }

    lines.push('## Behavioral Traits', '');
    lines.push(
      `- **Controversy**: ${soul.behavioral_traits.controversy_handling.replace(/-/g, ' ')}`
    );
    if (soul.behavioral_traits.signature_behaviors.length > 0) {
      lines.push('');
      lines.push('**Signature behaviors:**');
      for (const b of soul.behavioral_traits.signature_behaviors.slice(0, 8)) {
        lines.push(`- ${b}`);
      }
    }
    lines.push('');

    lines.push('## Knowledge Domains', '');
    if (soul.knowledge_domains.expert.length > 0) {
      lines.push(`**Expert**: ${soul.knowledge_domains.expert.join(', ')}`);
    }
    if (soul.knowledge_domains.familiar.length > 0) {
      lines.push(`**Familiar**: ${soul.knowledge_domains.familiar.join(', ')}`);
    }
    if (soul.knowledge_domains.blind_spots.length > 0) {
      lines.push(`**Blind spots**: ${soul.knowledge_domains.blind_spots.join(', ')}`);
    }

    return lines.join('\n');
  }

  private generateIdentityMd(persona: Persona, soul: Soul): string {
    return [
      `# ${persona.name}`,
      '',
      `> AI simulation created by Nico — for research and productivity use only.`,
      `> This agent simulates ${persona.name} based on public data. It is NOT the real person.`,
      '',
      '## Metadata',
      '',
      `- **Slug**: ${persona.slug}`,
      `- **Mode**: ${persona.mode === 'single' ? 'Single-person distill' : 'Multi-person fusion'}`,
      `- **Source targets**: ${persona.source_targets.join(', ')}`,
      `- **Training rounds**: ${soul.training_rounds_completed}`,
      `- **Memory nodes**: ${persona.memory_node_count}`,
      `- **Created**: ${persona.created_at}`,
      `- **Last trained**: ${persona.last_trained_at ?? 'never'}`,
      '',
      '## Usage',
      '',
      '```bash',
      `nico chat ${persona.slug}`,
      '```',
      '',
      '## Disclaimer',
      '',
      'This is an AI simulation, not the real person. Use responsibly.',
    ].join('\n');
  }

  private generateMemoryMd(persona: Persona): string {
    return [
      `# Memory Index: ${persona.name}`,
      '',
      `> ${persona.memory_node_count} memory nodes stored in Qdrant collection: \`${persona.memory_collection}\``,
      '',
      'Memory nodes are stored in the vector database and retrieved dynamically during conversation.',
      'To export full memory nodes, use:',
      '',
      '```bash',
      `nico export ${persona.slug} --to openclaw --include-memory`,
      '```',
    ].join('\n');
  }

  private generateAgentJson(soul: Soul, persona: Persona): string {
    const agentConfig = {
      schema_version: '1.0',
      agent: {
        id: persona.id,
        name: persona.name,
        slug: persona.slug,
        description: `AI simulation of ${soul.target_name} — created by Nico`,
        model: 'claude-haiku-4-5-20251001',
        tags: ['simulation', 'persona', ...soul.knowledge_domains.expert.slice(0, 5)],
        memory_collection: persona.memory_collection,
      },
      soul: {
        version: soul.version,
        confidence: soul.overall_confidence,
        top_beliefs: soul.values.core_beliefs.slice(0, 5).map((b) => b.belief),
        expertise: soul.knowledge_domains.expert,
        languages: soul.language_style.languages_used,
      },
      meta: {
        created_by: 'nico-agent',
        exported_at: new Date().toISOString(),
        disclaimer: 'AI simulation — not the real person',
      },
    };

    return JSON.stringify(agentConfig, null, 2);
  }

  private formalityLabel(level: number): string {
    if (level > 0.7) return 'formal';
    if (level > 0.4) return 'conversational';
    return 'casual';
  }
}
